# -*- coding: utf-8 -*-
"""Jenica pass/fail ML model.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1YNOIIfhAHs2__J-mxpANQtABfHhq1T-8
"""

base code:-

from sklearn.linear_model import LogisticRegression
import numpy as np

# X = hours studied, y = result (0 = Fail, 1 = Pass)
X = np.array([[1], [2], [3], [4], [5]])
y = np.array([0, 0, 0, 1, 1])

model = LogisticRegression()

model.fit(X, y)

hours = 3.5
prediction = model.predict([[hours]])
result = "Pass" if prediction[0] == 1 else "Fail"

print(f"Predicted result for {hours} hours of study: {result}")

expanded code:-

import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score
import matplotlib.pyplot as plt
from sklearn.preprocessing import StandardScaler

# Step 1: Create the dataset
data = {
    "Hours": [1,2,3,4,5,2.5,3.5,6,1.5,4.5,3,5.5,2,4,6.5,1.2,3.8,2.8,5.2,4.2],
    "Attendance": [40,60,50,70,80,55,60,90,45,75,65,85,50,68,92,42,70,55,88,73],
    "Sleep": [5,6,4,6,7,6,6,8,5,7,6,8,5,7,8,4,7,5,8,7],
    "Assignments": [30,40,20,60,70,50,55,90,30,80,60,85,35,70,95,25,65,40,90,75],
    "Result": [0,0,0,1,1,0,1,1,0,1,1,1,0,1,1,0,1,0,1,1]
}

df = pd.DataFrame(data)

# Step 2: Separate features and labels
X = df[["Hours", "Attendance", "Sleep", "Assignments"]]
y = df["Result"]

# Scale the data
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

# Step 3: Split data into training and testing
X_train, X_test, y_train, y_test = train_test_split(X_scaled, y, test_size=0.2, random_state=42)


# Step 4: Create and train the model
model = LogisticRegression()
model.fit(X_train, y_train)

# Step 5: Test the model
y_pred = model.predict(X_test)
accuracy = accuracy_score(y_test, y_pred)

print("Model Accuracy:", accuracy)

# Step 6: Try your own prediction
hours = 4.5
attendance = 70
sleep = 7
assignments = 80

# Scale the new prediction input using the trained scaler
new_data_scaled = scaler.transform([[hours, attendance, sleep, assignments]])
prediction = model.predict(new_data_scaled)[0]

result = "Pass" if prediction == 1 else "Fail"
print(f"\nPrediction for student: {result}")

# Step 7: Plot Hours vs Result
plt.scatter(df["Hours"], df["Result"])
plt.xlabel("Hours Studied")
plt.ylabel("Pass/Fail")
plt.title("Study Hours vs Result")
plt.show()

modified code:-

import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report
import matplotlib.pyplot as plt

# Step 1: Create the dataset
data = {
    "Hours": [1,2,3,4,5,2.5,3.5,6,1.5,4.5,3,5.5,2,4,6.5,1.2,3.8,2.8,5.2,4.2],
    "Attendance": [40,60,50,70,80,55,60,90,45,75,65,85,50,68,92,42,70,55,88,73],
    "Sleep": [5,6,4,6,7,6,6,8,5,7,6,8,5,7,8,4,7,5,8,7],
    "Assignments": [30,40,20,60,70,50,55,90,30,80,60,85,35,70,95,25,65,40,90,75],
    "Result": [0,0,0,1,1,0,1,1,0,1,1,1,0,1,1,0,1,0,1,1]
}

df = pd.DataFrame(data)

# Step 2: Separate features and labels
X = df[["Hours", "Attendance", "Sleep", "Assignments"]]
y = df["Result"]

# 🔥 Step 3: Scale/Normalize data (Improves model accuracy)
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

# Step 4: Split data
X_train, X_test, y_train, y_test = train_test_split(
    X_scaled, y, test_size=0.2, random_state=42
)

# Step 5: Create and train the model
model = LogisticRegression()
model.fit(X_train, y_train)

# Step 6: Test the model
y_pred = model.predict(X_test)
accuracy = accuracy_score(y_test, y_pred)

print("Model Accuracy:", accuracy)

# Step 7: New improved evaluation
print("\nConfusion Matrix:")
print(confusion_matrix(y_test, y_pred))

print("\nClassification Report:")
print(classification_report(y_test, y_pred))

# Step 8: Personal prediction example
hours = 4.5
attendance = 70
sleep = 7
assignments = 80

# ⚠️ IMPORTANT: also scale your custom input
new_data = scaler.transform([[hours, attendance, sleep, assignments]])

prediction = model.predict(new_data)[0]

result = "Pass" if prediction == 1 else "Fail"
print(f"\nPrediction for student: {result}")

# Step 9: Plot
plt.scatter(df["Hours"], df["Result"])
plt.xlabel("Hours Studied")
plt.ylabel("Pass/Fail")
plt.title("Study Hours vs Result")
plt.show()